build:
  environment:
    php: "8.1.2"
  nodes:
    analysis:
      tests:
        override:
          - "php-scrutinizer-run"

filter:
  paths: ["src/*"]
  excluded_paths: ["test/*"]
  dependency_paths: ["vendor/*"]

tools:
#  php_mess_detector: true
  php_code_sniffer:
    enabled: true
    config:
      standard: "psr1"
#  sensiolabs_security_checker: true
  # php_code_coverage: true
#  php_pdepend: true
#  php_loc:
#    enabled: true
#    excluded_dirs: ["test"]
#  php_cpd:
#    enabled: true
#    excluded_dirs: ["test"]
#  external_code_coverage:
#    timeout: 900

# vim: syntax=yaml ts=2 sw=2 et sr softtabstop=2 autoindent
