# https://docs.github.com/en/actions

name: "CI"

on: # yamllint disable-line rule:truthy
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
      - ".scrutinizer.yml"
      - ".editorconfig"
    branches: ["main"]
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
      - ".scrutinizer.yml"
      - ".editorconfig"
    branches: ["main"]

permissions:
  contents: "read"

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        php-version: [
          "8.1",
          "8.2",
          "8.3",
        ]
        composer-param: [
          "update --no-progress --prefer-dist --prefer-lowest",
          "update --no-progress --prefer-dist"
        ]
        experimental: [false]
        include:
          # also try a future version
          - php-version: "8.4"
            composer-param: "update --no-progress --prefer-dist --prefer-lowest"
            experimental: true
          - php-version: "8.4"
            composer-param: "update --no-progress --prefer-dist"
            experimental: true
    name: "PHP ${{ matrix.php-version }} test"
    steps:
      - name: "Check if PHP ${{ matrix.php-version }} is supported"
        if: "matrix.experimental == true"
        run: "echo 'PHP ${{ matrix.php-version }} is experimental'"
      - name: "checkout project"
        uses: "actions/checkout@v4"
        with:
          # needed by scrutinizer
          fetch-depth: 2

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "composer:v2"
          # needed by PHPUnit code coverage
          coverage: "pcov"

      - name: "Set up problem matchers for PHP"
        run: "echo \"::add-matcher::${{ runner.tool_cache }}/php.json\""

      - name: "Set up problem matchers for phpunit/phpunit"
        run: "echo \"::add-matcher::${{ runner.tool_cache }}/phpunit.json\""

      - name: "Get composer cache directory"
        id: "composer-cache"
        run: "echo \"dir=$(composer config cache-dir)\" >> $GITHUB_OUTPUT"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Cache composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "${{ runner.os }}-composer-"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Install dependencies"
        run: "composer ${{ matrix.composer-param }}"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --ansi --strict"
        continue-on-error: "${{ matrix.experimental }}"

      # Run phpunit with code coverage
      - name: "PHPUnit Tests"
        run: "vendor/bin/phpunit --colors=always --coverage-clover=coverage.clover"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Upload coverage reports to codecov.io"
        uses: "codecov/codecov-action@v4"
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
          slug: "teqneers/phpunit-stopwatch"
          files: "coverage.clover"

      # Uploading reports for analysis
      - name: "Upload code-coverage to scrutinizer"
        run: "vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Publish code coverage to Code Climate"
        uses: "paambaati/codeclimate-action@v5"
        env:
          CC_TEST_REPORTER_ID: "${{ secrets.CC_TEST_REPORTER_ID }}"
        with:
          coverageCommand: "vendor/bin/phpunit --coverage-clover=coverage.clover"
          coverageLocations: |
            coverage.clover:clover
        continue-on-error: "${{ matrix.experimental }}"

  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5

    strategy:
      matrix:
        php-version: ["8.3"]
        composer-param: ["update --no-progress --prefer-dist"]
        experimental: [false]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Lint YAML files"
        uses: "ibiqlik/action-yamllint@v3"
        with:
          config_file: ".yamllint.yaml"
          file_or_dir: "."
          strict: true

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "composer:v2"
          coverage: "none"

      - name: "Set up problem matchers for PHP"
        run: "echo \"::add-matcher::${{ runner.tool_cache }}/php.json\""

      - name: "Get composer cache directory"
        id: "composer-cache"
        run: "echo \"dir=$(composer config cache-dir)\" >> $GITHUB_OUTPUT"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Cache composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "${{ runner.os }}-composer-"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Install dependencies"
        run: "composer ${{ matrix.composer-param }}"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Run ergebnis/composer-normalize"
        run: "composer normalize --ansi --dry-run"

      - name: "Cache cache directory for friendsofphp/php-cs-fixer"
        uses: "actions/cache@v4"
        with:
          path: ".build/php-cs-fixer"
          key: "php-${{ matrix.php-version }}-php-cs-fixer-${{ github.ref_name }}"
          restore-keys: |
            php-${{ matrix.php-version }}-php-cs-fixer-main
            php-${{ matrix.php-version }}-php-cs-fixer-

      - name: "Run friendsofphp/php-cs-fixer"
        run: "vendor/bin/php-cs-fixer fix --ansi --config=.php-cs-fixer.php --diff --dry-run --show-progress=dots --verbose"

  dependency-analysis:
    name: "Dependency Analysis"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5

    strategy:
      matrix:
        php-version: ["8.3"]
        composer-param: ["update --no-progress --prefer-dist"]
        experimental: [false]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "phive"
          coverage: "none"

      - name: "Set up problem matchers for PHP"
        run: "echo \"::add-matcher::${{ runner.tool_cache }}/php.json\""

      - name: "Get composer cache directory"
        id: "composer-cache"
        run: "echo \"dir=$(composer config cache-dir)\" >> $GITHUB_OUTPUT"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Cache composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "${{ runner.os }}-composer-"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Install dependencies"
        run: "composer ${{ matrix.composer-param }}"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Create phive home directory"
        run: "mkdir -p .build/phive"
        shell: "bash"

      - name: "Cache dependencies installed with phive"
        uses: "actions/cache@v4.0.1"
        with:
          path: ".build/phive"
          key: "phive-hashFiles('**/phars.xml')"
          restore-keys: "phive-"

      - name: "Install dependencies with phive"
        env:
          PHIVE_HOME: ".build/phive"
        run: "phive --no-progress install --trust-gpg-keys 0x2DF45277AEF09A2F,0x033E5F8D801A2F8D,0x033E5F8D801A2F8D"
        shell: "bash"

      - name: "Run maglnet/composer-require-checker"
        run: ".phive/composer-require-checker check --ansi --config-file=$(pwd)/composer-require-checker.json --verbose"

  refactoring:
    name: "Refactoring"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5

    strategy:
      matrix:
        php-version: ["8.3"]
        composer-param: ["update --no-progress --prefer-dist"]
        experimental: [false]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "composer:v2"
          coverage: "none"

      - name: "Set up problem matchers for PHP"
        run: "echo \"::add-matcher::${{ runner.tool_cache }}/php.json\""

      - name: "Get composer cache directory"
        id: "composer-cache"
        run: "echo \"dir=$(composer config cache-dir)\" >> $GITHUB_OUTPUT"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Cache composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "${{ runner.os }}-composer-"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Install dependencies"
        run: "composer ${{ matrix.composer-param }}"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Cache directory for rector/rector"
        uses: "actions/cache@v4"
        with:
          path: ".build/rector"
          key: "php-${{ matrix.php-version }}-rector-${{ github.ref_name }}"
          restore-keys: |
            php-${{ matrix.php-version }}-rector-main
            php-${{ matrix.php-version }}-rector-

      - name: "Run automated refactoring with rector/rector"
        run: "vendor/bin/rector --ansi --config=rector.php --dry-run"

  security-analysis:
    name: "Security Analysis"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5

    strategy:
      matrix:
        php-version: ["8.3"]
        composer-param: ["update --no-progress --prefer-dist"]
        experimental: [false]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "composer:v2"
          coverage: "none"

      - name: "Set up problem matchers for PHP"
        run: "echo \"::add-matcher::${{ runner.tool_cache }}/php.json\""

      - name: "Get composer cache directory"
        id: "composer-cache"
        run: "echo \"dir=$(composer config cache-dir)\" >> $GITHUB_OUTPUT"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Cache composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "${{ runner.os }}-composer-"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Install dependencies"
        run: "composer ${{ matrix.composer-param }}"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Cache directory for rector/rector"
        uses: "actions/cache@v4"
        with:
          path: ".build/rector"
          key: "php-${{ matrix.php-version }}-rector-${{ github.ref_name }}"
          restore-keys: |
            php-${{ matrix.php-version }}-rector-main
            php-${{ matrix.php-version }}-rector-

      - name: "Check installed packages for security vulnerability advisories"
        run: "composer audit --ansi"

  static-code-analysis:
    name: "Static Code Analysis"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5

    strategy:
      matrix:
        php-version: ["8.3"]
        composer-param: ["update --no-progress --prefer-dist"]
        experimental: [false]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "composer:v2"
          coverage: "none"

      - name: "Set up problem matchers for PHP"
        run: "echo \"::add-matcher::${{ runner.tool_cache }}/php.json\""

      - name: "Get composer cache directory"
        id: "composer-cache"
        run: "echo \"dir=$(composer config cache-dir)\" >> $GITHUB_OUTPUT"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Cache composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "${{ runner.os }}-composer-"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Install dependencies"
        run: "composer ${{ matrix.composer-param }}"
        continue-on-error: "${{ matrix.experimental }}"

      - name: "Cache directory for rector/rector"
        uses: "actions/cache@v4"
        with:
          path: ".build/rector"
          key: "php-${{ matrix.php-version }}-rector-${{ github.ref_name }}"
          restore-keys: |
            php-${{ matrix.php-version }}-rector-main
            php-${{ matrix.php-version }}-rector-

      - name: "Run vimeo/psalm"
        run: "vendor/bin/psalm --config=psalm.xml --output-format=github --shepherd --show-info=false --stats --threads=4"

# vim: syntax=yaml ts=2 sw=2 et sr softtabstop=2 autoindent
